load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "PDC_USS",
    srcs = ["PDC_USS.cc"],
    hdrs = [
        "PDC_USS.h",
        "//opendbc/can:common_dbc.h",
    ],
)