load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test", "cc_binary")

package(default_visibility = ["//visibility:public"])

cc_library(
  name = "params",
  hdrs = ["params.h"],
)

cc_library(
  name = "point",
  hdrs = ["point.h"],
)

cc_library(
  name = "ultrasonic_orientation",
  hdrs = ["ultrasonic_orientation.h"],
)
